apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-side
  namespace: aether
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: aether
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outbox-relay
  namespace: aether
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processor
  namespace: aether
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-engine
  namespace: aether
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasource
  namespace: aether
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: aether
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-dashboard
  namespace: aether
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: aether
spec:
  strategy:
    type: Recreate
