apiVersion: v1
kind: Secret
metadata:
  name: aether-secrets
  namespace: aether
stringData:
  AETHER_DB_URL: jdbc:postgresql://aether-demo-pg.postgres.database.azure.com:5432/aetherstream
  AETHER_DB_PASSWORD: REPLACE_WITH_KEYVAULT_OR_CI_SECRET
