apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: aether
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.0.10
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8085
      targetPort: 8085
